# Generated by Django 6.0.4 on 2026-05-02 13:27

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 3, 13, 26, 52, 896410, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='status',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewed_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='status',
            name='image',
            field=models.ImageField(default='not given', upload_to='status/'),
            preserve_default=False,
        ),
    ]
