# Generated by Django 6.0.4 on 2026-05-02 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_status_expires_at_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 3, 14, 2, 2, 996272, tzinfo=datetime.timezone.utc)),
        ),
    ]
