# Generated by Django 6.0.4 on 2026-05-02 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_group_admin_groupmessage_file_alter_group_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 3, 15, 42, 58, 190400, tzinfo=datetime.timezone.utc)),
        ),
    ]
