# Generated by Django 6.0.4 on 2026-05-02 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_groupmessage_is_read_alter_status_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hg_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 3, 16, 4, 52, 231036, tzinfo=datetime.timezone.utc)),
        ),
    ]
