# Generated by Django 6.0.4 on 2026-05-03 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_status_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 4, 3, 35, 27, 446956, tzinfo=datetime.timezone.utc)),
        ),
    ]
