# Generated by Django 6.0.4 on 2026-05-03 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_alter_status_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 4, 4, 24, 30, 648855, tzinfo=datetime.timezone.utc)),
        ),
    ]
