# Generated by Django 6.0.4 on 2026-05-03 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_alter_status_expires_at_activitylog_onlineuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 4, 10, 36, 31, 847450, tzinfo=datetime.timezone.utc)),
        ),
    ]
