# Generated by Django 6.0.4 on 2026-05-04 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_alter_status_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 5, 6, 31, 52, 424023, tzinfo=datetime.timezone.utc)),
        ),
    ]
